### ISSUE TITLE
Some tests in atlas/aod/test_integrated_query.py fail when using a marker

### ISSUE THREAD

**Issue by sudo-panda** [iris-hep/func_adl_xAOD#124]
These tests fail when the command `pytest -m "atlas_xaod_runner"` is run:

- test_select_first_of_array
- test_two_simultaneous_runs
- test_First_two_outer_loops
- test_not_in_where

This is because the CMS AOD EventCollections are also sourced along with ATLAS xAOD ones when looking for the marker.

**Comment by gordonwatts** [comment]
These tests are failing because both CMS and ATLAS tests are setting `cpp_ast.method_names` with the same things (like `Jet` or `Muons` or similar.

And `cpp_ast.method_names` is a global variable - or behaves like one here.

Some comments on this:
- In practice, one will never be running both at the same time - so this is just an issue with testing, not with how things are actually running.
- It does mean we can't really export both the cms and the atlas executor from the top level - as that causes them both to be loaded.

Options for fixing:

- Make sure `cpp_ast.method_names` (and the type system) aren't global variables and rather are some sort of type system object that is passed around.
   - This is a lot of work and will touch many tests
   - It is probably "the right thing to do" given that global variables are bad - for this very reason - often.
- Reset the global variables after each test, and trigger (somehow) the loading of the items.
   - This would mean creating a function for each set of types that need to be added and calling it in the global space.
   - Then after a reset, the appropriate items would need to be called to re-load the global space in a test init method.
 
Given the second solution does not preclude eventually converting to the first, let's go that route.

Here is the way to do this (I think):

1) Create a function for all type system initialization methods. For everything that isn't ATLAS or CMS specific, have the function called in the global scope
1) For the things that are atlas or cms specific, figure out the proper place to trigger them
1) All tests should still be working as well as they were before at this point.
1) Create a `reset` method in the type system that clears all the global variables
1) Create a post-test fixture for files that use the type system that calls the reset, and then re-inits all the non-atlas/cms specific types
1) At this point all tests should work again, and further, we should be able to run both the ATLAS and CMS tests.
